### ISSUE TITLE
[Main] 메인 페이지에 사용되는 api 구현

### ISSUE THREAD

**Issue by yeriinnn** [Plick-pop-in/poppin-be#1]
## ISSUE
- 메인 페이지에 사용되는 api 구현

## To-do
- [x]  진행중인 팝업(스토어) 랜덤 이미지 조회(자동 슬라이드 5개)
- [x]  진행중인 팝업 top 3 조회
- [x] 진행중인 전국 팝업 스토어 조회
