### ISSUE TITLE
[User] 회원가입 & 로그인 기능 구현

### ISSUE THREAD

**Issue by GimHaLim** [Plick-pop-in/poppin-be#8]
## ISSUE
- 회원가입 & 로그인 기능 구현

## To-do
- [x]  로그인 -> JWT 토큰 발행 및 검증
- [ ]  회원 가입
- [ ]  아이디 찾기
- [ ]  비밀번호 찾기
- [ ]  이메일 중복 확인
- [ ]  닉네임 중복 확인
- [ ]  닉네임 수정
- [ ]  비밀번호 수정

## 참고사항 및 체크포인트
